service: translate-telegram-bot

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post